---
title: "DSC540 Term Project"
author: "A. Kendell Davis"
date: "5/27/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r Game.Census.Climate.Data}
library(tidyverse)
read.csv("C:/Users/mithr/Desktop/Data Science Masters/DSC 540/Term Project/Game-Census-Climate Data.csv")
region <- Game.Census.Climate.Data$Region
location <- Game.Census.Climate.Data$Location
households <- Game.Census.Climate.Data$Total.households
medianhome <- Game.Census.Climate.Data$Median.household.income..dollars...in.2018.inflation.adjusted.dollars.
meanhome <- Game.Census.Climate.Data$Mean.household.income..dollars...in.2018.inflation.adjusted.dollars.
familyhouse <- Game.Census.Climate.Data$Total.family.households
medianfamily <- Game.Census.Climate.Data$Median.family.income..dollars...in.2018.inflation.adjusted.dollars.
meanfamily <- Game.Census.Climate.Data$Mean.family.income..dollars...in.2018.inflation.adjusted.dollars.
percapita <- Game.Census.Climate.Data$Per.capita.income..dollars...in.2018.inflation.adjusted.dollars.
nonfamilyhouse <- Game.Census.Climate.Data$Total.nonfamily.households
mediannonfamily <- Game.Census.Climate.Data$Median.nonfamily.income..dollars...in.2018.inflation.adjusted.dollars.
meannonfamily <- Game.Census.Climate.Data$Mean.nonfamily.income..dollars...in.2018.inflation.adjusted.dollars.
medianworkearn <- Game.Census.Climate.Data$Median.earnings.for.workers..dollars...in.2018.inflation.adjusted.dollars.
medianmaleearn <- Game.Census.Climate.Data$Median.earnings.for.male.full.time..year.round.workers..dollars...in.2018.inflation.adjusted.dollars.
medianfemearn <- Game.Census.Climate.Data$Median.earnings.for.female.full.time..year.round.workers..dollars...in.2018.inflation.adjusted.dollars.
totalpop <- Game.Census.Climate.Data$Total.population.16..years
laborpop <- Game.Census.Climate.Data$Population.16..years.in.labor.force
civillaborpop <- Game.Census.Climate.Data$Population.16..years.in.civilian.labor.force
monthyear <- Game.Census.Climate.Data$Month.and.Year
totalprecip <- Game.Census.Climate.Data$Total.precipitation..inches.
avgtemp <- Game.Census.Climate.Data$Average.temperature..Â.F.
game <- Game.Census.Climate.Data$Game
Steamowners <- Game.Census.Climate.Data$Total.Steam.owners..range.
meanplayforever <- Game.Census.Climate.Data$Mean.Playtime.since.March.2009..minutes.
meanplay2weeks <- Game.Census.Climate.Data$Mean.Playtime.for.Last.Two.Weeks..minutes.
medianplayforever <- Game.Census.Climate.Data$Median.Playtime.since.March.2009..minutes.
medianplay2weeks <- Game.Census.Climate.Data$Median.Playtime.for.Last.Two.Weeks..minutes.
```
```{r}
ggplot(data = Game.Census.Climate.Data, aes(households,medianhome)) + geom_jitter(aes(color = region, shape = Steamowners))
```

```{r}
ggplot(data = Game.Census.Climate.Data, aes(x = Steamowners, y = laborpop)) + geom_col(aes(fill = region), position = "dodge")
```

```{r}
ggplot(data = Game.Census.Climate.Data, aes(totalprecip, avgtemp)) + geom_line(aes(color=region))
```


```{r}
ggplot(data = Game.Census.Climate.Data, aes(meanplayforever, totalpop)) + geom_area(aes(color=region, fill=region))
```

```{r}
ggplot(data = Game.Census.Climate.Data, aes(Steamowners, medianplayforever)) + geom_col(aes(color=region, fill=region), position = "stack")
```
